### ISSUE TITLE
SID Emulation 

### ISSUE THREAD

**Issue by daitangio** [irmen/pyc64#3]
Hi, I like very much pyc64, I has the project I am looking for and I blogged it too
https://gioorgi.com/2019/commodore-retro/

I am exploring a way to add a SID-like sound capability to the emulator.
There are little python library to emulate the SID, mostly interface some SID players and so on.
reSID emulator (writte in C++) is very good but no python interface is out of there. Also it seems a lot CPU hungry.

A nice try should be integrating with the SonicPi which by the way is a way more powerful

https://pypi.org/project/python-sonic/

What do you think?
Are you already tried some of this library? 
Suggestions?

**Comment by irmen** [comment]
I love the SID !
It is awesome to attempt to integrate it into pyc64 but:
- pyc64 is a simulator, not an emulator, so it's not bad to not have c64 like sound capability, (but still it would be awesome if it had it)
- pyc64 has very few dependencies and is pure python so Sid play support must be purely optional

**Comment by daitangio** [comment]
Yes my goal is to make the SID chip completely optional.
I have no luck finding a SonicPi implementation of C/64 SID, I asked to Sam Aaron, so I am still exploring this idea.
I'd like to implement a pyc64 to SonicPi gateway, trying to emulate a bit the SID but not with much fidelity (it is not easy to do).
I have little sound knowledge, I should study a way more SonicPi before being able to do it.

**Comment by irmen** [comment]
I've got a Python softsynth project as well that could be integrated to create simple oscillator based sounds.... :thinking:

**Comment by daitangio** [comment]
Think about it and let me know if it can be integrated, we can set up a "feature" branch and see if it is worth to. SonicPi is very nice because it is very flexible: we can have multiple SIDs, very powerful effect and so on

**Comment by irmen** [comment]
That SonicPi looks to be quite awesome

**Comment by daitangio** [comment]
Yes its engine is SuperCollider, a real time music synthetizer. I have already hooked SonicPi using a library called python-sonic you can see my branch "feature/c32-experiment" but it is a very embrional state right now. I'd like to link SID Voice 1 to some Sonic Pi effect and try it out with a demo basic program

**Comment by irmen** [comment]
Closing this at it seems to be too far-fetched anyway.

**Comment by cyberic99** [comment]
maybe this implementation of the SID chip in python could be useful?

https://github.com/Gadgetoid/python-sidchip

(it uses bindings against reSID)

**Comment by irmen** [comment]
I have no desire to pursue this further, but maybe someone else will, so thanks for that link
