### ISSUE TITLE
Ideas for further expansion

### ISSUE THREAD

**Issue by daitangio** [irmen/pyc64#9]
Hi Irmen, I'd like to extend pyc64's real mode in the right direction :)
So far I have started exploring some ideas, but I'd like to share my thoughts here for the best results:

1.  A "Learning mode". I have started developing a "tracing mode" to print out KERNAL and BASIC
     entry points
     https://github.com/daitangio/pyc64/tree/feature/learn-mode
     It is easy to tune because it read a simple CSV file to tag the addresses, and you can turn it on/off via a toggle button (ugly but effective).

2.  Some way to speed up 6502 emulator. I'd like to stick with a python implementation, but I had trouble to get pypy working (I was unable to compile it so far). The other way is to link a C-implementation to python, but it seems to go against the "pure-python" implementation of pyc64.

3. Create a "virtual" device, I called "Device23" to be able to do http request (like to "open" a web site and get a page on some way).
The goal is to have the BASIC V2 able doing something like
    **OPEN 1,23,0,"www.cbm.com"** 
    **INPUT#1,INDEX$**
to get the web page (or a PETASCII representation of it)
I started experimenting with the KERNAL High and low level API but I was unable to understand what is the best way of implementing a virtual device.
I ended up to trap the low level calls              
    + KERNAL Send LISTEN Command on Serial Bus
    + KERNAL Send LISTEN Secondary Addres
    + KERNAL Send Data On Serial Bus
and to intercept the high level one, but it is far beyond my skills (see **run_rom_code** under 
https://github.com/daitangio/pyc64/commit/e6fc9643977e4b858e47878c4a419a6f96674335 )

4. Other ideas (i.e. dos wedge implemented in python?)

**Comment by irmen** [comment]
I love your ideas
1) sounds like advanced type of breakpoints or cpu tracing?
2) i won't bother compiling pypy yourself. Just use a precompiled version. It greatly increases execution speed around 5x on my machine.   Also the 6502 emulation is not my project but a 3rd party library. I once tried to optimize it a bit by profiling but decided it wasn't worth my time then because I could simply  use pypy
3) that is REALLY interesting. And a lot of work I think.  Do you have the annotated ROM disassembly and programming manuals of the C64 and such?
4) before attempting this I suggest making the "breakpoint intercepter" code more generic first. In my Kotlin c64 emulator I did this, you can register code callbacks on certain memory locations as breakpoints. It's already what you're doing with the load/save routine but those are hardcoded now

**Comment by daitangio** [comment]
> I love your ideas
> 
> 1. sounds like advanced type of breakpoints or cpu tracing?

Yes, it is working and you can dinamically reload the csv with the trace location.

> 2. i won't bother compiling pypy yourself. 

I was able to download  a pypy3 precompiled and verified it speed up a lot 6502 emulator.
I added README with a list of steps to get up and running with pip and the pillow libraries.
(see commit ddb611dc3d3346f38a6dd791740eda3076c215aa)

> 3. that is REALLY interesting. And a lot of work I think.  Do you have the annotated ROM disassembly and programming manuals of the C64 and such?

I got  "All_About_Your_64"  by "The Dreams" but it seems a bit cryptic.
Michael Steil's blog post https://www.pagetable.com/?p=1031 describe the workflow with great detail, but I must reverse-eng. KERNAL's Zeropage logical file descriptors to find out where are kept file logical data to intercept the right call. 
It is a time consumer task right now.

**Do you have some documentation/wiki to point me?**

In this trace example, I find out $F157  with logical channel 5 seems a good intercept point,but  I must do further analysis:

>FFBD KERNAL Set Filename A = len                               - A=$10 X=$20 Y=$08 P=%00110000 SP=F6
>** Reading filename (if A=0 ignore it) www.c64-wiki.com
>FFC0 KERNAL Open a logical file                                - A=$10 X=$20 Y=$08 P=%00110000 SP=F6
>[...]
>E112 KERNAL Input Character                                    - A=$05 X=$00 Y=$00 P=%00110010 SP=F2
>FFCF KERNAL CHRIN       Input character from channel    byte -> A       - A=$05 X=$00 Y=$00 P=%00110010 SP=F0
>F157 KERNAL Input a byte                                       - A=$05 X=$00 Y=$00 P=%00110010 SP=F0


> 4. before attempting this I suggest making the "breakpoint intercepter" code more generic first. In my Kotlin c64 emulator I did this, you can register code callbacks on certain memory locations as breakpoints. It's already what you're doing with the load/save routine but those are hardcoded now

I will look your code and add some fine-grained hooks.

**Comment by irmen** [comment]
additional links I have used in the past:

http://unusedino.de/ec64/technical/project64/mapping_c64.html
https://www.pagetable.com/c64ref/c64disasm/
http://www.ffd2.com/fridge/docs/c64-diss.html

**Comment by daitangio** [comment]
Hi, Mapping 64 is very well written.
I was able to understand a bit more how to implement Device23.
I will look forward on it in my spare time
